### ISSUE TITLE
Update corefoundation to latest

### ISSUE THREAD

**Issue by searls** [fcheung/keychain#16]
Ruby 3.1 started emitting errors in ffi finalizers to stderr and the version of corefoundation this gem is pegged to (`~>0.2.0`) had a bug that resulted in these being noisily emitted repeatedly:

```
warning: Exception in finalizer #<CF::Base::Releaser:0x0000000104693570 @address=105553129341824>
/Users/justin/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/corefoundation-0.2.0/lib/corefoundation/base.rb:55:in `release': :pointer argument is not a valid pointer (ArgumentError)
```

It was fixed in corefoundation https://github.com/chef/corefoundation/issues/35 in 0.3.13. Would you consider upgrading?

**Comment by fcheung** [comment]
Not trivially I'm afraid - in between 0.2 and 0.2 some core aspects of the memory model changed & I get a ton of segfaults if i upgrade, (even after stripping out a lot of memory releasing so that the code should run (albeit leaking like a sieve) - see https://github.com/fcheung/keychain/pull/18

**Comment by searls** [comment]
Bummer. Thanks

**Comment by fcheung** [comment]
the finalizer stuff is actually pretty trivial - i'll try backporting that to 0.2 at some point this weekend

**Comment by fcheung** [comment]
I made a start on that, however i think the finalizer blowing up has been hiding a real issue with memory being over-released

**Comment by fcheung** [comment]
The fix is included in the version I just pushed. Thanks for pointing this out!
