### ISSUE TITLE
Release new gem version and add tags

### ISSUE THREAD

**Issue by legal90** [fcheung/keychain#3]
@fcheung Thank you for this useful gem!
I'm gonna use it for automation purposes, in community "cookbook" for Chef (https://chef.io), the popular configuration management tool.

Could you please release a new version of 'ruby-keychain' on rubygems.org? It will allow us to get the latest changes.

Also, adding a git tags to this repo will make a release cycle a little bit clearer and will help other contributors to track changes between different versions.

**Comment by fcheung** [comment]
Sure - no problem

https://rubygems.org/gems/ruby-keychain/versions/0.2.1

**Comment by legal90** [comment]
Thanks! 

P.s. Could you help please - is it possible to import new certificate from the `.cer` or `.p12` to the keychain using this gem? I found that `Keychain::Item.new` can do it, but I can't figure out how to get `SecKeychainItemRef` pointer or cert attributes from a file. :-(

**Comment by fcheung** [comment]
I don't think that's implemented - the person that implemented the item / certificate stuff only needed to export. I believe you'd need to write some wrappers around SecItemImport  - patches welcome :-)
